mqtt:
  broker: "localhost" #Replace with dynamic public IPv4 address of ec2 instance
  port: 1884

telegram:
  bot_token: "7804241350:AAHqGGrZzzU3jtx3GBsCwDIJ3siqpLJNh-k" #Replace with bot token
  chat_id: "123456789"  # Replace with your chat ID
