mqtt:
  broker: "localhost" #Not required to replace this if the script is running on EC2 , replace it with public IPv4 address of the EC2 instance while running locally.
  port: 1884

telegram:
  bot_token: "7804241350:AAHqGGrZzzU3jtx3GBsCwDIJ3siqpLJNh-k" #Replace with bot token
  chat_id: "8190888160"  # Replace with your chat ID
