mqtt:
  broker: "localhost" #Not required to replace this as the scripts are run in the ec2 instance
  port: 1884

telegram:
  bot_token: "7804241350:AAHqGGrZzzU3jtx3GBsCwDIJ3siqpLJNh-k" #Replace with bot token
  chat_id: "8190888160"  # Replace with your chat ID